import { getBlogPost } from "@/app/actions";
import ReactMarkdown from "react-markdown";
import rehypeRaw from "rehype-raw";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Calendar, Tag } from "lucide-react";

const categoryGradients: Record<string, string> = {
    "Predictie": "from-blue-600 to-cyan-500",
    "Diagnostiek": "from-purple-600 to-pink-500",
    "Methodisch": "from-green-600 to-emerald-500",
    "Ethiek": "from-orange-600 to-amber-500",
    "default": "from-gray-900 to-gray-700"
};

export default async function BlogPostPage({ params }: { params: Promise<{ id: string }> }) {
    const { id } = await params;
    const blog = await getBlogPost(id);

    if (!blog) {
        notFound();
    }

    const gradient = categoryGradients[blog.category] || categoryGradients["default"];

    return (
        <article className="min-h-screen bg-white pb-20">
            {/* Hero Header */}
            <div className={`relative h-[50vh] min-h-[400px] flex items-end`}>
                {/* Dynamic Gradient Background */}
                <div className={`absolute inset-0 bg-gradient-to-br ${gradient}`} />

                {/* Abstract Shapes for Texture */}
                <div className="absolute top-0 right-0 w-full h-full overflow-hidden opacity-20 pointer-events-none">
                    <div className="absolute -top-1/2 -right-1/2 w-[100%] h-[100%] bg-white rounded-full blur-3xl" />
                    <div className="absolute -bottom-1/2 -left-1/2 w-[100%] h-[100%] bg-black rounded-full blur-3xl" />
                </div>

                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent z-10" />

                {/* Back Button - Positioned at top */}
                <div className="absolute top-24 left-0 w-full z-30">
                    <div className="container section-padding">
                        <Link
                            href="/"
                            className="inline-flex items-center gap-2 text-white/90 hover:text-white transition-colors backdrop-blur-md bg-white/10 border border-white/20 px-4 py-2 rounded-full font-medium text-sm hover:bg-white/20"
                        >
                            <ArrowLeft size={16} />
                            Back to Home
                        </Link>
                    </div>
                </div>

                <div className="container relative z-20 pb-16 section-padding text-white">
                    <div className="flex flex-wrap items-center gap-4 mb-6">
                        <span className="px-4 py-1.5 rounded-full bg-white/20 backdrop-blur-md text-sm font-bold tracking-wide border border-white/20 shadow-sm">
                            {blog.category}
                        </span>
                        <span className="flex items-center gap-2 text-white/90 text-sm font-medium">
                            <Calendar size={16} />
                            {new Date(blog.createdAt).toLocaleDateString("nl-NL", {
                                year: 'numeric',
                                month: 'long',
                                day: 'numeric'
                            })}
                        </span>
                    </div>

                    <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight max-w-5xl drop-shadow-sm">
                        {blog.title}
                    </h1>
                </div>
            </div>

            {/* Content */}
            <div className="container section-padding -mt-12 relative z-30">
                <div className="bg-white rounded-3xl p-8 md:p-12 shadow-xl border border-gray-100 max-w-4xl mx-auto">
                    <div className="prose prose-lg prose-slate max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-blue-600 hover:prose-a:text-blue-800 prose-img:rounded-2xl prose-img:shadow-md">
                        <ReactMarkdown rehypePlugins={[rehypeRaw]}>{blog.content}</ReactMarkdown>
                    </div>

                    {/* Footer / Share / Related could go here */}
                    <div className="mt-16 pt-8 border-t border-gray-100">
                        <p className="text-gray-500 italic text-sm">
                            Generated by Medical AI based on recent research.
                        </p>
                    </div>
                </div>
            </div>
        </article>
    );
}
